name: Deploy Node.js App to Docker Nginx

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest   # Must be your local machine with Docker running

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Install dependencies (optional if using build step)
      - name: Install Node dependencies
        run: |
          npm install

      # 3️⃣ Build app (optional, only if you have a build step)
      # Uncomment if needed
      # - name: Build app
      #   run: |
      #     npm run build

      # 4️⃣ Copy public files to Nginx container
      - name: Copy files to Nginx
        run: |
          docker cp ./public/. mysite-nginx:/usr/share/nginx/html

      # 5️⃣ Reload Nginx to serve new files
      - name: Reload Nginx
        run: |
          docker exec mysite-nginx nginx -s reload
