name: Deploy Node.js Express App to Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest   # Your PC with Docker

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 1: Build Docker image
    - name: Build Docker image
      run: |
        docker build -t mynode-app .

    # Step 2: Stop existing container (if any)
    - name: Stop existing container
      run: |
        docker stop mynode-app || true
        docker rm mynode-app || true

    # Step 3: Run new container
    - name: Run Docker container
      run: |
        docker run -d -p 3000:3000 --name mynode-app mynode-app
