name: Deploy to Docker Nginx

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Copy app files into the Nginx container
      - name: Copy files to Nginx
        run: |
          # Replace 'mysite' with your build folder if using React/Vite etc.
          docker cp ./mysite/. mysite-nginx:/usr/share/nginx/html

      # 3️⃣ Reload Nginx inside the container
      - name: Reload Nginx
        run: |
          docker exec mysite-nginx nginx -s reload
