name: Deploy Node.js behind Nginx

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Build Node.js image
    - run: docker build -t mynode-app .

    # Stop/remove old Node container
    - run: |
        if [ $(docker ps -aq -f name=mynode-app) ]; then
          docker stop mynode-app
          docker rm mynode-app
        fi

    # Run Node.js container
    - run: docker run -d --name mynode-app mynode-app

    # Stop/remove old Nginx container
    - run: |
        if [ $(docker ps -aq -f name=mynode-nginx) ]; then
          docker stop mynode-nginx
          docker rm mynode-nginx
        fi

    # Run Nginx container (reverse proxy to Node)
    - run: |
        docker run -d -p 8080:80 \
          --link mynode-app:mynode-app \
          -v /path/to/nginx.conf:/etc/nginx/conf.d/default.conf:ro \
          --name mynode-nginx nginx
