name: Deploy Node.js Express App to Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Build Docker image
    - name: Build Docker image
      run: |
        docker build -t mynode-app .

    # Step 3: Stop and remove old container if it exists
    - name: Stop old container if exists
      run: |
        if [ $(docker ps -aq -f name=mynode-app) ]; then
          docker stop mynode-app
          docker rm mynode-app
        fi

    # Step 4: Run new container
    - name: Run Docker container
      run: |
        docker run -d -p 3000:3000 --name mynode-app mynode-app
